
services:
    
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            # Mount the local config file into the container
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            # Use a named volume for persistent data storage
            - prometheus_data:/prometheus
        ports:
            - "9090:9090"

volumes:
    prometheus_data: