all:
  children:
    slaves:
      hosts:
        server-4:
          ansible_host: 10.11.12.4
          ansible_user: intrig
        # Adicione os demais hosts aqui seguindo o mesmo padrão:
        # nome-da-maquina:
        #   ansible_host: IP_DA_MAQUINA
