all:
  children:
    slaves:
      hosts:
        maquina-01:
          ansible_host: 10.0.0.10
        maquina-02:
          ansible_host: 10.0.0.11
        # Adicione os demais hosts aqui seguindo o mesmo padrão:
        # nome-da-maquina:
        #   ansible_host: IP_DA_MAQUINA
